### ISSUE TITLE
Erweiterungen

### ISSUE THREAD

**Issue by quorle** [Pittini/iobroker-Timer#1]
Ich hätte eventuell noch einige gute Verbesserungen oder Erweiterungen:

1. Du hast nur eine Anwesenheitserkennung. Leider habe ich hier zwei, jeweils einen Datenpunkt für jede Person. Hier wäre es vielleicht noch super, wenn das mit in dein Script aufgenommen wird. Also sprich mehrere Datenpunkte für die Anwesenheit.
2. Zudem wäre es vielleicht noch super, wenn man dein Script so erweitert, dass wenn einer bald zu Hause ist ( wird bei mir über Geofency gesetzt ), dass dann der Schaltpunkt nach Ablauf einer eingestellten Zeit schaltet.
3. Könnte man noch zu jedem Schaltpunkt eine individuelle Abschaltzeit hinzufügen.

**Comment by Pittini** [comment]
1. Das ist ein Timerskript kein Anwesenheitsskript. Die Anwesenheitsfunktion bezieht sich auf den Timer damit z.B. keine Lampen geschaltet werden wenn keiner da ist. Wann keiner da ist hat ein Anwesenheitsskript zu entscheiden.
2. Auch das hat eigentlich nix mit nem Timerskript zu tun, siehe .1
3. Nein, sicher nicht, das würde ein völlig anderes Konzept vorraussetzen und ist in etlichen Fällen einfach überflüssig. Z.B. werden hier bei Sonnenuntergang die Lampen angeschaltet, ausgeschaltet aber nur manuell wenn ich ins Bett geh. Wenn doch auch ausgeschaltet werden soll,  einfach über nen 2ten Timereintrag.
