### ISSUE TITLE
Timer-Widget Portierung auf iobroker lovelace-card.

### ISSUE THREAD

**Issue by manni-2x** [Pittini/iobroker-Timer#11]
Hallo,

ich benutze den Timer in iObroker-vis und es wäre mein großer Wunsch den vis-widget auf iobroker-lovelace-card zu portieren.

Das dürfte doch mit nicht so großem Aufwand möglich sein -  der Timer Javascript könnte unverändert bleiben?

Der Grund ist dass ich mittlerweile beinahe komplett - bis auf den Timer vom Vis auf iobroker-lovelace umgestiegen bin.

MfG
Marian

**Comment by Pittini** [comment]
Hab zwar keine Ahnung von Lovelace, aber es spricht eigentlich nix dagegen dass es klappen sollte. Am Skript muißte nix ändern imho.
