### ISSUE TITLE
Umlaute

### ISSUE THREAD

**Issue by totocotonio** [Pittini/iobroker-Timer#3]
Hallo,
kann es sein, das das Script nicht umlauten umgehen kann.
Ich habe einen Ordner der "Meine Geräte" heißt.
Ein Datenpunkt dort heraus funktioniert nicht.

javascript.0 | 2020-07-03 10:16:27.860 | error | (31723) at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
javascript.0 | 2020-07-03 10:16:27.860 | error | (31723) at runMicrotasks (<anonymous>)
javascript.0 | 2020-07-03 10:16:27.860 | error | (31723) at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
javascript.0 | 2020-07-03 10:16:27.860 | error | (31723) at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
javascript.0 | 2020-07-03 10:16:27.860 | error | (31723) at /opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93703
javascript.0 | 2020-07-03 10:16:27.860 | error | (31723) at /opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1910:38
javascript.0 | 2020-07-03 10:16:27.860 | error | (31723) at Object.<anonymous> (script.js.common.Service.Timer:207:17)
javascript.0 | 2020-07-03 10:16:27.859 | error | (31723) at main (script.js.common.Service.Timer:448:5)
javascript.0 | 2020-07-03 10:16:27.859 | error | (31723) at init (script.js.common.Service.Timer:428:82)
javascript.0 | 2020-07-03 10:16:27.859 | error | (31723) Error in callback: TypeError: Cannot read property 'common' of null
javascript.0 | 2020-07-03 10:16:27.857 | warn | (31723) Object "javascript.0.Meine_Geräte" does not exist
javascript.0 | 2020-07-03 10:16:27.857 | info | (31723) script.js.common.Service.Timer: Reaching Init()
javascript.0 | 2020-07-03 10:16:27.857 | info | (31723) script.js.common.Service.Timer: Reaching Main
javascript.0 | 2020-07-03 10:16:27.857 | info | (31723) script.js.common.Service.Timer: Initial CreateStates finished!
javascript.0 | 2020-07-03 10:16:27.813 | info | (31723) script.js.common.Service.Timer: registered 0 subscriptions and 0 schedules
javascript.0 | 2020-07-03 10:16:27.812 | info | (31723) script.js.common.Service.Timer: Starting TimerSkript V2.1.4
javascript.0 | 2020-07-03 10:16:27.809 | info | (31723) Start javascript script.js.common.Service.Timer
javascript.0 | 2020-07-03 10:16:26.627 | info | (31723) Stop script script.js.common.Service.Timer

**Comment by Pittini** [comment]
Umlaute sollten nicht das Problem sein, das Log deutet eher auf nen ungültigen Channel hin. Zeig mal wo und wie der Meine_Geräte Channel angelegt ist.

**Comment by totocotonio** [comment]
Sobald ich den Datenpunkt anwähle, wird das script gelb.

Mache ich ihn wieder raus alles gut.

![timer kaffee](https://user-images.githubusercontent.com/48123111/86472504-8d557a00-bd3f-11ea-9e61-2b408f57963c.png)




javascript.0 | 2020-07-03 15:50:30.123 | error | (31723) at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
javascript.0 | 2020-07-03 15:50:30.122 | error | (31723) at runMicrotasks (<anonymous>)
javascript.0 | 2020-07-03 15:50:30.122 | error | (31723) at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
javascript.0 | 2020-07-03 15:50:30.122 | error | (31723) at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
javascript.0 | 2020-07-03 15:50:30.122 | error | (31723) at /opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93703
javascript.0 | 2020-07-03 15:50:30.122 | error | (31723) at /opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1910:38
javascript.0 | 2020-07-03 15:50:30.122 | error | (31723) at Object.<anonymous> (script.js.common.Service.Timer:207:17)
javascript.0 | 2020-07-03 15:50:30.122 | error | (31723) at main (script.js.common.Service.Timer:448:5)
javascript.0 | 2020-07-03 15:50:30.122 | error | (31723) at init (script.js.common.Service.Timer:428:82)
javascript.0 | 2020-07-03 15:50:30.122 | error | (31723) Error in callback: TypeError: Cannot read property 'common' of null
javascript.0 | 2020-07-03 15:50:30.120 | warn | (31723) Object "javascript.0.Meine_Geräte" does not exist
javascript.0 | 2020-07-03 15:50:30.120 | info | (31723) script.js.common.Service.Timer: Reaching Init()
javascript.0 | 2020-07-03 15:50:30.120 | info | (31723) script.js.common.Service.Timer: Reaching Main
javascript.0 | 2020-07-03 15:50:30.119 | info | (31723) script.js.common.Service.Timer: Initial CreateStates finished!
javascript.0 | 2020-07-03 15:50:30.117 | info | (31723) script.js.common.Service.Timer: registered 0 subscriptions and 0 schedules
javascript.0 | 2020-07-03 15:50:30.110 | info | (31723) script.js.common.Service.Timer: Starting TimerSkript V2.1.4
javascript.0 | 2020-07-03 15:50:30.099 | info | (31723) Start javascript script.js.common.Service.Timer
javascript.0 | 2020-07-03 15:50:28.507 | info | (31723) script.js.common.Service.Timer: Timer Schedule 1 killed
javascript.0 | 2020-07-03 15:50:28.503 | info | (31723) Stop script script.js.common.Service.Timer

**Comment by Pittini** [comment]
Dacht ichs mir doch, was Du da angelegt hast ist so nicht ganz korrekt auch wenns mit einfacheren Skripts klappen mag. Es fehlt ne Untergruppierung und es fehlt ein Channel. Ich hab sowas auch, vergleich mal:
![Inked2020-07-03 15_52_03-objects - ioBroker_LI](https://user-images.githubusercontent.com/51408942/86475681-6bf78c80-bd45-11ea-9fad-3f8359dc125f.jpg)

**Comment by totocotonio** [comment]
ok,
das wusste ich nicht.
Bei mir funktioniert so alles.
Ich kann das alles nicht ändern, da ich dort keinen "Stift" zum ändern habe.

Da heisst ich müsste alle datenpunkte neu anlegen.

**Comment by Pittini** [comment]
> Ich kann das alles nicht ändern, da ich dort keinen "Stift" zum ändern habe.

Genau das ist das Problem, deswegen kann das Skript auch nicht richtig zugreifen. Es versucht den vom DAtenpunkt aus gesehen übergeordneten Channel anzusprechen und den gibts quasi nicht. Außerdem isses ohnehin nicht sauber weil Du dem Gerät auch keinen channel gegeben hast. Sobald jetzt die Kaffemaschine nen 2ten DP kriegen soll (warum auch immer) haste ein Problem.
Ändern kannste aber übrigens auch ohne "Stift" via JS. Isn Einzeiler und sieht zb. so aus:
`setObject("javascript.0.Meine_Geräte", {type: 'channel', common: {name: 'Ich bin ein Channel'}, native:{}});`

Danach haste dann auch nen Stift ;)

**Comment by totocotonio** [comment]
Hi,
vielen Dank für den Hinweis.

So das habe ich gemacht. Jetzt steht dort überall "ich bin ein Channel" das gerät ist aber augewählt
![script](https://user-images.githubusercontent.com/48123111/86517338-7a6aa480-be28-11ea-8d95-acdb0c78928f.png)

**Comment by Pittini** [comment]
> Jetzt steht dort überall "ich bin ein Channel" das gerät ist aber augewählt

Naja, ich dachte dasses klar ist, dass das ein Demo Text zum anpassen ist. Das kommt jetzt eben davon dass Du keine Devicechannels hast, das Skript nimmt immer den Namen des übergeordneten Channel und wenn der "ich bin ein channel" heißt, dann zeigt halt genau das an. Kannst ja jederzeit ändern.

**Comment by totocotonio** [comment]
Hallo,
vielleicht verstehen wir uns falsch.
Ich habe den Channel nur "Testweise" geändert. Ich muss doch nicht für jedes device das in dem Ordner meine Geräte liegt einen eigenen Device Channel machen.

Der Ziel Name müsste doch in diesem Fall "Kaffeemaschine "heißen.  Weil alle geräte die ich in diesem Ordner zuweise,
heißen dann alle "Ich bin ein Channel"

**Comment by Pittini** [comment]
> Ich muss doch nicht für jedes device das in dem Ordner meine Geräte liegt einen eigenen Device Channel machen.

Doch, wenn Dus richtig machen willst schon, macht auch jeder Adapter so, nicht ohne Grund.

> Der Ziel Name müsste doch in diesem Fall "Kaffeemaschine "heißen. 

Nein, darauf greift das Skript nicht zu, weil wenns richtig gemacht ist, ist das ja nur ein Datenpunkt der z.B. Power heißt. Der Gerätenamen steht immer im übergeordneten Device.

**Comment by Pittini** [comment]
In der letzten Version gibts ne Einstellung dazu. Zeile 10 auf false setzen, dann nimmer er direkt die Namen aus den Dps.
