### ISSUE TITLE
error while using 0_userdata as praefix

### ISSUE THREAD

**Issue by harrym67** [Pittini/iobroker-Timer#4]
const praefix = "javascript.0.Timer."; //Grundpfad is working fine.

when using 0_userdata as praefix the DPs TimerCount, TimerCountText and TimerCountValues get nulled an also the DPs SwitchTarget and SwitchTargetName for the first two timers become also nulled.

**Comment by Pittini** [comment]
I think, its not an Script Issue. The support for 0_userdata is very new, and im not sure if its fully native supported by the JS Adapter, an when, at which version. Please use the javascript.0.xxx path or create an Issue at the js adapter.
