### ISSUE TITLE
Fehler beim Schalten von MQTT Objekten

### ISSUE THREAD

**Issue by BigDi** [Pittini/iobroker-Timer#7]
Wollte über den MQTT Client ein State schalten. Dieses State hat kein Objekt als Parent sondern nur Ordnerstrukturen.
Ich vermute deswegen kommen dann auch diese Fehler:

javascript.0 | 2020-12-07 15:38:30.653 | error | (17561)     at process._tickCallback (internal/process/next_tick.js:68:7)
-- | -- | -- | --
javascript.0 | 2020-12-07 15:38:30.652 | error | (17561)     at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
javascript.0 | 2020-12-07 15:38:30.652 | error | (17561)     at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
javascript.0 | 2020-12-07 15:38:30.652 | error | (17561)     at (anonymous function).get (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93703)
javascript.0 | 2020-12-07 15:38:30.652 | error | (17561)     at adapterObjects.getObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2870:21)
javascript.0 | 2020-12-07 15:38:30.652 | error | (17561)     at /opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1943:38
javascript.0 | 2020-12-07 15:38:30.651 | error | (17561)     at Object.<anonymous> (script.js.TimerSwitch:211:17)
javascript.0 | 2020-12-07 15:38:30.651 | error | (17561)     at main (script.js.TimerSwitch:460:5)
javascript.0 | 2020-12-07 15:38:30.651 | error | (17561)     at init (script.js.TimerSwitch:436:86)
javascript.0 | 2020-12-07 15:38:30.650 | error | (17561) Error in callback: TypeError: Cannot read property 'common' of null
javascript.0 | 2020-12-07 15:38:30.647 | warn | (17561) Object "mqtt-client.0.cmnd.FHEM.IT_V3_2590a6c0" does not exist
javascript.0 | 2020-12-07 15:38:30.646 | info | (17561) script.js.TimerSwitch: GetParentId(Targets[y])=mqtt-client.0.cmnd.FHEM.IT_V3_2590a6c0

**Comment by Pittini** [comment]
Genau dieses Problem hatten wir grad im Forum. https://forum.iobroker.net/topic/33228/vorlage-flexibles-timerskript-vis/306
Die Lösung ist letztendlich nen channel zu machen wie er sein sollte, isn Einzeilerskript (den Pfad bitte anpassen), einmal ausführen und gut.
`setObject("mqtt.0.SmartHome.Gosund4.cmnd", { type: 'channel', common: { name: "" }, native: {} }); //Channel machen`

**Comment by BigDi** [comment]
Dieser Fehler konnte durch die Änderung des Typs behoben werden.
