### ISSUE TITLE
Cannot render view Pool_Pumpe. Invalid settings

### ISSUE THREAD

**Issue by TheDmDLP** [Pittini/iobroker-Timer#9]
Wenn ich die TimerView.txt importiere, bekomme ich die Fehlermeldung als Popup: Cannot render view Pool_Pumpe. Invalid settings. Alle andern Views sind leer und erst ein Löschen von der importierten TimerView.txt beseitigt das Problem. Keine Fehler im Log gefunden dazu.

**Comment by Pittini** [comment]
Bitte etwas mehr Infos. Wie genau machst Du den Import? Was ist Pool_Pumpe, den Begriff gibts bei mir nirgends?

**Comment by TheDmDLP** [comment]
Ich importiere die TimerView.txt unverändert. ( hier im git öffnen als raw alles kopieren und importieren im vis) Poolpumpe ist lediglich der Begriff für meine vis Page. also wie sie heissen soll nach dem importieren.
![image](https://user-images.githubusercontent.com/11164995/132321813-60b0d181-fa26-40b2-bff5-6055f3246993.png)

**Comment by Pittini** [comment]
Sorry wenn ich das jetzt so hart sage, aber wer lesen kann is klar im Vorteil. Punkt 5 der Installation sagt ausdrücklich Import via "Widgets importieren" und Du machst "View importieren".

**Comment by TheDmDLP** [comment]
OMG.. ich hab das total überlesen... 3x die Anleitung nachgelesen und nicht gemerkt das ich das falsch gelesen hab.. Sorry .. ich hatte es nämlich schon am laufen und wollte es nur updaten/neu einrichten... einmal mehr liegt der Fehler am Anwender..
